export const LOADED_WEB3 = 'LOADED_WEB3';
export const LOADED_ACCOUNT = 'LOADED_ACCOUNT';
export const LOADED_NETWORK = 'LOADED_NETWORK';
export const LOADED_TOKEN_CONTRACT = 'LOADED_TOKEN_CONTRACT';
export const LOADED_EXHANGER_CONTRACT = 'LOADED_EXHANGER_CONTRACT';
